name: yassay
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09679
title: YassaY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#303030'
    - '#b2b2b2'
    - '#8f8f8f'
    - '#d7d7d7'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
