name: yassay
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52052
title: YassaY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.7215496704448014
  rhythmicContrast: 1
purpose: []
